# Define your own admin routes here

acme_awesome_service:
    resource: |
        alias: acme_awesome.service
        section: admin
        templates: '@SyliusAdmin/Crud'
        grid: acme_awesome.service
        redirect: index
    type: sylius.resource
