# Delete these routes and define your own shop routes here

acme_sylius_awesome_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: Acme\SyliusAwesomePlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

acme_sylius_awesome_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: Acme\SyliusAwesomePlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~
